### ISSUE TITLE
crash when pressing the create button in the vehicle crafting table

### ISSUE THREAD

**Issue by kotmatross28729** [Unknown025/Flans-Mod-Plus#175]
Happens even with only flans installed (no packs)
In the vehicle crafting table, you need to press the create button (even if there are no packs) and the game will crash

## video:

https://user-images.githubusercontent.com/110309314/224534456-76969a55-c43f-4eea-8e42-d81a93709322.mp4

## crash report: https://pastebin.com/UYwRwSzV

**Comment by GoldSloth** [comment]
Thanks for reporting this. It should be a straightforward fix.

**Comment by GoldSloth** [comment]
This should be fixed by 30d4644df8fbe69431817d0648490e2f1c0ecd3d, thanks for reporting it :)

**Comment by kotmatross28729** [comment]
Sorry for the long answer, but it seems to me that the problem is still present (flans was build today, from latest commit)
This time the error is already  NPE
## Crash report: https://pastebin.com/sgVGRnp5

**Comment by GoldSloth** [comment]
Thanks,.sorry I missed that before

**Comment by GoldSloth** [comment]
I believe this issue would be caused when there is no content pack with an engine in it - ie you need to install simple parts pack, or another parts pack with engines.

It's something we'll fix in the long term, but probably won't now.

If that's not the case, and you do have a parts pack with an engine, please let me know and I'll look into it. 

Thanks :)

**Comment by kotmatross28729** [comment]
The crash report shows the loaded mods:


UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar)
UCHIJAAAA Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar)
UCHIJAAAA CodeChickenCore{1.1.11} [CodeChickenCore] (minecraft.jar)
UCHIJAAAA flansmod{1.56} [Flan's Mod Ultimate] (Flan's Mod Ultimate Stability Edition-1.56.jar)
UCHIJAAAA mechapartspack{1.56} [Mecha Parts Pack] (Mecha Parts-Content Pack-1.56.jar)
**`UCHIJAAAA simplepartspack{1.56} [Simple Parts Pack] (Simple Parts-Content Pack-1.56.jar)`**
UCHIJAAAA titanpack{1.56} [Titan Pack] (Titan-Content Pack-1.56.jar)
UCHIJAAAA zombiepack{1.56} [Zombie Pack] (Zombie-Content Pack-1.56.jar)


This error exists both with and without it.

**Comment by GoldSloth** [comment]
That's very odd...  Are all these packs the standard content mods? It not, please could you send them to me.

And are you trying to craft in single player or multiplayer, (or does it happen in both), do you put any parts in the table? and is it all vehicles that do this?

**Comment by kotmatross28729** [comment]
These are standard packs from the output folder when building the mod, it happens in a single game (I didn’t check it in multiplayer, but most likely there too)
To reproduce, you just need to put the table on the ground and click on the "Craft" button, you don't need to choose or put anything there.

**Comment by GoldSloth** [comment]
This should be fixed now - my apologies for not diagnosing this properly before. Basically, it allowed you to proceed in creative if you didn't have an engine in your inventory, but didn't assign a default engine - so crashed. I've just added a bit of code to select a default engine, which should solve it.

I'd be grateful if you could test it and confirm, before I say it's fixed this time :)

676709f13235bd53325daa6069dce519c56cebb5

**Comment by kotmatross28729** [comment]
Oops, sorry again for such a late (a whole week!) reply. And yes, the last commit solved the problem!
Thank you!
